FROM quay.io/keycloak/keycloak:26.0

ADD --chmod=644 https://github.com/galaxyproject/keycloak-galaxy-user-provider/releases/download/v0.1.0/galaxy-user-provider.jar \
    /opt/keycloak/providers/galaxy-user-provider.jar

COPY --chmod=755 init-galaxy-scope.sh /opt/keycloak/init-galaxy-scope.sh
