---

ssh_private_keys: "{{ vault_ssh_private_keys }}"

ssh_host_keys:
  thumper.galaxyproject.org: thumper.galaxyproject.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO12pjb3M7VyFVAZuIinev1TWWERunqILNsxbczELQQh
  orval.galaxyproject.org: orval.galaxyproject.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAkpUCs6Z/urs1agezYQmqb/JzJFGNweeSE68nycoXcA
  cvmfs0-psu1.galaxyproject.org: cvmfs0-psu1.galaxyproject.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrczgsw6Lvud9Cze2I/GD61re39BMewhTCVmIJMWLBa
