---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_files:
  - dest: /etc/idmapd.conf
    content: |
      [General]
      Domain = galaxyproject.org
    owner: root
    group: root
    mode: "0644"

host_templates:
  - dest: /etc/rsyncd.conf
    src: ini.j2
    contents:
      software:
        path: /srv/nginx/depot.galaxyproject.org/root/software
        comment: Community Package Cache
        use chroot: 'yes'
        uid: 'nobody'
        gid: 'nogroup'
        read only: 'yes'
        list: 'yes'
        dont compress: '*.tgz *.zip *.gz *.bz2 *.bam *.2bit *.lzo'
      singularity:
        path: /srv/nginx/depot.galaxyproject.org/singularity
        comment: BioContainers Singularity Images
        use chroot: 'yes'
        uid: 'nobody'
        gid: 'nogroup'
        read only: 'yes'
        list: 'yes'
        dont compress: '*'

host_packages:
  - nfs-common
  - rsync

host_mounts:
  - src: depot-srv.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root
    path: /srv/nginx/depot.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,rw,soft,timeo=300
    state: mounted
    backup: yes
    owner: depot
    group: depot
  - src: orval.galaxyproject.org:/data/orval/depot/singularity
    path: /srv/nginx/depot.galaxyproject.org/singularity
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,rw,soft,timeo=300
    state: mounted
    backup: yes
    owner: singularity
    group: singularity
  - src: depot-srv.galaxyproject.org:/srv/nginx/snpeff-data.galaxyproject.org/root
    path: /srv/nginx/snpeff-data.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: root
    group: root
  - src: depot-srv.galaxyproject.org:/srv/nginx/bioarchive.galaxyproject.org/root
    path: /srv/nginx/bioarchive.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: bioarchive
    group: bioarchive
  - src: depot-srv.galaxyproject.org:/srv/nginx/images.galaxyproject.org/root
    path: /srv/nginx/images.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: sites
    group: sites
  - src: depot-srv.galaxyproject.org:/srv/nginx/sample-data.galaxyproject.org/root
    path: /srv/nginx/sample-data.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: sites
    group: sites
  - src: depot-srv.galaxyproject.org:/srv/nginx/wheels.galaxyproject.org/root
    path: /srv/nginx/wheels.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: sites
    group: sites
  - src: depot-srv.galaxyproject.org:/srv/nginx/screencast.galaxyproject.org/root
    path: /srv/nginx/screencast.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: sites
    group: sites
  - src: depot-srv.galaxyproject.org:/srv/nginx/eggs.galaxyproject.org/root
    path: /srv/nginx/eggs.galaxyproject.org/root
    fstype: nfs4
    opts: x-systemd.automount,x-systemd.idle-timeout=600,_netdev,ro,soft,timeo=300
    state: mounted
    backup: yes
    owner: sites
    group: sites

host_users:
  - "{{ galaxyproject_users.depot }}"
  - "{{ galaxyproject_users.depot_singularity }}"
  - "{{ galaxyproject_users.depot_sites }}"
  - "{{ galaxyproject_users.depot_bioarchive }}"
  - "{{ galaxyproject_users.depot_training }}"
  - "{{ galaxyproject_users.depot_starforge }}"

host_groups:
  - "{{ galaxyproject_groups.depot }}"
  - "{{ galaxyproject_groups.depot_singularity }}"
  - "{{ galaxyproject_groups.depot_sites }}"
  - "{{ galaxyproject_groups.depot_bioarchive }}"
  - "{{ galaxyproject_groups.depot_training }}"
  - "{{ galaxyproject_groups.depot_starforge }}"

host_services:
  - name: rsync
    state: started
    enabled: true

host_kernel_params:
  - name: net.ipv4.tcp_congestion_control
    value: bbr
  - name: net.core.default_qdisc
    value: fq
  - name: net.core.rmem_max
    value: 134217728
  - name: net.core.wmem_max
    value: 134217728
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 67108864
  - name: net.ipv4.tcp_wmem
    value: 4096 65536 67108864

nginx_conf_http:
  server_names_hash_bucket_size: 64

nginx_conf_ssl_protocols:
  - TLSv1.2
  - TLSv1.3

nginx_servers:
  - certbot_redirects
  - eggs

nginx_ssl_servers:
  - rochefort
  - snpeff-data
  - screencast
  - images
  - sample-data
  - bioarchive
  - depot
  - eggs-ssl

certbot_redirect_domains:
  - "{{ inventory_hostname }}"
  - snpeff-data.galaxyproject.org
  - screencast.galaxyproject.org
  - screencast.g2.bx.psu.edu
  - images.galaxyproject.org
  - sample-data.galaxyproject.org
  - bioarchive.galaxyproject.org
  - depot.galaxyproject.org

certbot_domains:
  - "{{ inventory_hostname }}"
  - snpeff-data.galaxyproject.org
  - screencast.galaxyproject.org
  - screencast.g2.bx.psu.edu
  - images.galaxyproject.org
  - sample-data.galaxyproject.org
  - bioarchive.galaxyproject.org
  - depot.galaxyproject.org
  - eggs.galaxyproject.org
  - eggs.g2.bx.psu.edu
