---

# ESVs name your packages consistently challenge level: impossible
sentinelone_deb: >-
  {{ (ansible_architecture == 'aarch64') | ternary(
    'https://admin.bx.psu.edu/sentinelone/SentinelAgent-aarch64_linux_aarch64_v25_4_2_21.deb',
    'https://admin.bx.psu.edu/sentinelone/SentinelAgent_linux_x86_64_v25_4_2_21.deb'
  ) }}
sentinelone_packages:
  - sentinelagent
