---

os_public_network: public

os_network:
  name: "usegalaxy"
  subnet:
    name: "usegalaxy"
    cidr: 10.0.0.0/22
  router:
    name: "usegalaxy"
    network: "{{ os_public_network }}"
    interfaces:
      # the openstack router module will attempt to detach any unlisted subnets, so this needs to be exhaustive even if we don't configure all of these subnets here
      - "usegalaxy"
      - "development"

# FUTURE WARNING: I had originally shared these with a test project using the CLI. When I then used this to share them
# for production via the role, it updated the existing policies to the new project, which should not be correct. So if
# we ever wanted to share with another project, that could be an issue.
os_neutron_rbac_policies:
  # usegalaxy network
  - object_id: 343ca6f2-22b0-4744-8787-6b8105e71b04
    object_type: network
    project_id: 7f24a65ae719452baddb6aa0896b339f         # MCB140147
    action: access_as_shared
    target_project_id: 0e70a73d5a49406e8f47f2be62bec592  # BIO250460 (VGP)
  # usegalaxy-node security group
  - object_id: 2732c540-aa21-489b-9ce2-80be999cb1ff
    object_type: security_group
    project_id: 7f24a65ae719452baddb6aa0896b339f         # MCB140147
    action: access_as_shared
    target_project_id: 0e70a73d5a49406e8f47f2be62bec592  # BIO250460 (VGP)

os_security_group_rules:
  - name: usegalaxy-node
    rules:
      - direction: ingress
        protocol: any
        ether_type: IPv4
        remote_group: usegalaxy-node
      - direction: ingress
        protocol: any
        ether_type: IPv6
        remote_group: usegalaxy-node
  - name: usegalaxy-control
    rules:
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        remote_ip_prefix: 129.114.60.0/24
        port_range_min: 1
        port_range_max: 65535
      - protocol: udp
        remote_ip_prefix: 129.114.60.0/24
        port_range_min: 1
        port_range_max: 65535
      - protocol: udp
        remote_ip_prefix: 129.114.60.0/24
        port_range_min: 1
        port_range_max: 65535
  - name: cvmfs
    rules:
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 3128
        port_range_max: 3128
  - name: litellm
    rules:
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        remote_ip_prefix: 129.114.60.0/24
        port_range_min: 443
        port_range_max: 443
      # BRC VMs
      - protocol: tcp
        remote_ip_prefix: 129.114.102.0/24
        port_range_min: 443
        port_range_max: 443
