#!/bin/sh
set -e

LOG_DIR=/var/log/slurm/launch

[ ! -d $LOG_DIR ] && mkdir -p $LOG_DIR

(
set -xv

VENV=/opt/slurm_cloud_provision
PLAYBOOK=/opt/slurm_cloud_provision/infrastructure-playbook

: ${HOME:=/var/lib/slurm}
export HOME

. $VENV/bin/activate
cd $PLAYBOOK
instances=`scontrol show hostnames "$1" | tr '\n' ',' | sed 's/,$//'`
ansible-playbook -i jetstreamiuenv/instance_inventory jetstreamiuenv/terminate.yml --vault=/var/lib/slurm/.vault-pass --extra-vars="jetstream_instances_to_terminate=$instances"
) 2>&1 | tee "$LOG_DIR/terminate`date +%s`.${1}.log"
true
